# Generated by Django 4.2.7 on 2023-11-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Default', max_length=100)),
                ('last_name', models.CharField(default='Default', max_length=100)),
                ('suffix', models.CharField(default='Default', max_length=100)),
                ('email', models.EmailField(default='Default@default.com', max_length=254)),
                ('status', models.CharField(default='Default', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(default='Default', max_length=500)),
                ('question_title', models.CharField(default='Default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice', models.TextField(default='default', max_length=1000)),
                ('position', models.IntegerField(verbose_name='position')),
                ('question', models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.questiontext')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('question', 'Choice'), ('question', 'position')},
            },
        ),
    ]
