# Generated by Django 4.2.7 on 2023-11-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Default', max_length=100)),
                ('last_name', models.CharField(default='Default', max_length=100)),
                ('suffix', models.CharField(default='Default', max_length=100)),
                ('email', models.EmailField(default='Default@default.com', max_length=254)),
                ('status', models.CharField(default='Default', max_length=500)),
                ('status_desc', models.TextField(default='Default', max_length=500)),
                ('university', models.CharField(default='Default', max_length=100)),
                ('university_desc', models.TextField(default='Default', max_length=500)),
                ('department', models.CharField(default='Default', max_length=100)),
                ('university_title', models.CharField(default='Default', max_length=100)),
                ('university_link', models.CharField(default='Default', max_length=100)),
                ('semantic_scholar', models.CharField(default='Default', max_length=100)),
                ('google_scholar', models.CharField(default='Default', max_length=100)),
                ('research_tagline', models.CharField(default='Default', max_length=300)),
                ('research_description', models.CharField(default='Default', max_length=150)),
                ('research_count', models.CharField(default='Default', max_length=100)),
                ('research_example', models.TextField(default='Default', max_length=500)),
                ('data_science_class_1', models.CharField(default='Default', max_length=100)),
                ('data_science_class_2', models.CharField(default='Default', max_length=100)),
                ('data_science_class_3', models.CharField(default='Default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(default='Default', max_length=500)),
                ('question_title', models.CharField(default='Default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('choice', models.CharField(default='default', max_length=100)),
                ('question', models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.questiontext')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('question', 'position'), ('question', 'choice')},
            },
        ),
    ]
