# Generated by Django 4.2.7 on 2023-11-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_choice_questionchoice_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='first_name',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
