# Generated by Django 4.2.7 on 2023-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_questionresponse_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='status_desc',
            field=models.CharField(default='Default', max_length=500),
        ),
    ]
