# Generated by Django 4.2.7 on 2023-11-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_questionresponse_data_science_class_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresponse',
            old_name='reserach_count',
            new_name='research_count',
        ),
    ]
